project:
  type: website
  output-dir: docs

website:
  title: "Damian Marciniak's R Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/DamianMarciniak2005/rcc_quarto
      - icon: linkedin
        href: https://www.linkedin.com/in/damian-marciniak-0928a5214 
format:
  html:
    theme: minty
    css: styles.css

editor: visual

